# Site settings
title: Tobias Schneider
email: tobiasjschneider@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Copyright Tobias Schneider 2015. All rights reserved.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://tobyschneider.com" # the base hostname & protocol for your site
twitter_username: tobyschneider
github_username:  tobyschneider

# Build settings
markdown: kramdown
